//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThomsonReuters.Eikon.STOpsConsole.PlatformUsageDataCollector {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatformUsageDataCollector.IPlatformUsageDataCollector")]
    public interface IPlatformUsageDataCollector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessage", ReplyAction="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageRespo" +
            "nse")]
        void WriteOpsConsoleDesktopMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessage", ReplyAction="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageRespo" +
            "nse")]
        System.Threading.Tasks.Task WriteOpsConsoleDesktopMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageLzma", ReplyAction="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageLzmaR" +
            "esponse")]
        void WriteOpsConsoleDesktopMessageLzma(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageLzma", ReplyAction="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageLzmaR" +
            "esponse")]
        System.Threading.Tasks.Task WriteOpsConsoleDesktopMessageLzmaAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageGzip", ReplyAction="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageGzipR" +
            "esponse")]
        void WriteOpsConsoleDesktopMessageGzip(System.IO.Stream message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageGzip", ReplyAction="http://tempuri.org/IPlatformUsageDataCollector/WriteOpsConsoleDesktopMessageGzipR" +
            "esponse")]
        System.Threading.Tasks.Task WriteOpsConsoleDesktopMessageGzipAsync(System.IO.Stream message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlatformUsageDataCollectorChannel : ThomsonReuters.Eikon.STOpsConsole.PlatformUsageDataCollector.IPlatformUsageDataCollector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatformUsageDataCollectorClient : System.ServiceModel.ClientBase<ThomsonReuters.Eikon.STOpsConsole.PlatformUsageDataCollector.IPlatformUsageDataCollector>, ThomsonReuters.Eikon.STOpsConsole.PlatformUsageDataCollector.IPlatformUsageDataCollector {
        
        public PlatformUsageDataCollectorClient() {
        }
        
        public PlatformUsageDataCollectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatformUsageDataCollectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformUsageDataCollectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformUsageDataCollectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteOpsConsoleDesktopMessage(string message) {
            base.Channel.WriteOpsConsoleDesktopMessage(message);
        }
        
        public System.Threading.Tasks.Task WriteOpsConsoleDesktopMessageAsync(string message) {
            return base.Channel.WriteOpsConsoleDesktopMessageAsync(message);
        }
        
        public void WriteOpsConsoleDesktopMessageLzma(string message) {
            base.Channel.WriteOpsConsoleDesktopMessageLzma(message);
        }
        
        public System.Threading.Tasks.Task WriteOpsConsoleDesktopMessageLzmaAsync(string message) {
            return base.Channel.WriteOpsConsoleDesktopMessageLzmaAsync(message);
        }
        
        public void WriteOpsConsoleDesktopMessageGzip(System.IO.Stream message) {
            base.Channel.WriteOpsConsoleDesktopMessageGzip(message);
        }
        
        public System.Threading.Tasks.Task WriteOpsConsoleDesktopMessageGzipAsync(System.IO.Stream message) {
            return base.Channel.WriteOpsConsoleDesktopMessageGzipAsync(message);
        }
    }
}
